### ISSUE TITLE
Requests for updates to the presentation converter

### ISSUE THREAD

**Issue by swcurran** [andrewwhitehead/anoncreds-w3c-mapping#1]
Could you please make the follow updates to the presentation converter:

- add `issueanceDate` as per the W3C VC spec. It should be `now()`.
- add a `type` to the `credentialSchema` item. I'm not sure what that should be -- let me know if that is a non-trivial thing to do.
- turn the W3C output into a Verifiable Presentation, with the Aggregate proof as the VP `proof`. This is similar to what Daniel proposed.

Reasonable?

Thanks!

**Comment by andrewwhitehead** [comment]
I believe this is all sorted now
